#!/bin/bash

PUBLIC_IP=$(oc-metadata --cached PUBLIC_IP_ADDRESS)

cat <<EOF
Hi Cloud Rider,
Welcome to the Ruby on Rails InstantApp, the following are installed
and configured:
- Rails
- Ruby
- Rvm
- Nginx
- Unicorn
- Node.js
The default rails app is in /home/rails/default and online at http://${PUBLIC_IP}/
Useful links:
- https://github.com/scaleway-community/scaleway-rails
Enjoy!
EOF
